### ISSUE TITLE
D&D 3.5, New token appears for a second then disappears

### ISSUE THREAD

**Issue by Daltoro** [p4535992/foundryvtt-automated-polymorpher#12]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 9.269
* How Are You Using Foundry: Chrome
* Which Game System: d&d 3.5
* Modules Enabled?: yes i had 36 active, but i just try with Polymorph and require module, and don't work with that

### Issue Description

Hey, I play on d&d 3.5 and I found this module for a friend of mine who plays a werewolf, so perfect for this transformation, the problem is that when I did the tests on my side (in my part with the 36 modules activated, and in another that I created just for testing) I have the transformation menu, and when I activate a transformation, the new token appears for a second then disappears and the old token returns, but the name of the new token still remains. I tried several things but nothing to do, do you have a solution?
Thank you in advance and have a nice day

**Comment by p4535992** [comment]
@Daltoro 
If is not dnd5e is probably a warpgate issue, but le me do some test. 
Can you pass to me the two actors ?
Renamed the json file with ".txt" for attach on github

**Comment by Daltoro** [comment]
[fvtt-Actor-theo.txt](https://github.com/p4535992/foundryvtt-automated-polymorpher/files/8952104/fvtt-Actor-theo.txt)
[fvtt-Actor-theo-humain.txt](https://github.com/p4535992/foundryvtt-automated-polymorpher/files/8952105/fvtt-Actor-theo-humain.txt)

**Comment by Daltoro** [comment]
Hey! I'm coming to take some news, have you found a part for a solution, or have you been busy lately? Thank you in advance and good day ! :)

**Comment by p4535992** [comment]
i'll probably make a new release this weekend, for solve this and other issues.

**Comment by Daltoro** [comment]
Hey! I just saw that you updated! The problem is solved and the transformer works well, despite that I have another small bug suddenly, each time my token transforms, it creates a copy of that character sheet, how to solve the problem?
Thank you in advance and good day !

**Comment by p4535992** [comment]
For now i can't avoid to create that actor, until i understand why warpgate has that strange behaviour.
it should be automatically deleted when you right click on the hud button (revert polymorph).

**Comment by p4535992** [comment]
try the last release

**Comment by Daltoro** [comment]
Not Working :/

**Comment by p4535992** [comment]
is working on my test world, click f12 and tell me if there is any error on the web console.
Make sure to have the module settings "Force use of wargate" disabled.

**Comment by Daltoro** [comment]
Module settings is disabled
and yes i had on error : 

Uncaught (in promise) TypeError: targetActor.toJSON is not a function
    at Object.transformInto (D35E.js:83:45)
    at Object.callback (D35E.js:627:36)

**Comment by p4535992** [comment]
Try out version 1.0.43.
