### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by turlang** [p4535992/foundryvtt-automated-polymorpher#16]
**Module Version:** v0.0.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 

**Game System:** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

ERROR
dnd5e.js:83 Uncaught (in promise) TypeError: targetActor.toJSON is not a function
[Detected 1 package: automated-polymorpher]
    at Object.transformInto (dnd5e.js:83:45)
    at Object.callback (dnd5e.js:597:36)

**Comment by p4535992** [comment]
Try out version 1.0.43.
