### ISSUE TITLE
No Revert Transformation Button[BUG]

### ISSUE THREAD

**Issue by CasualTerror** [p4535992/foundryvtt-automated-polymorpher#17]
**Module Version:** v1.0.41

**Describe the bug**
When I transform a token the revert transformation button is missing. If I keep transforming the token into different forms the token name gets longer (Name)(Name2)(Name3)(Name4). It quickly gets long and Foundry starts to lag.

**To Reproduce**
1. Transform token (Polymorph)(Wild Shape)(Alter Self)(Custom) doesn't matter which type of transformation

**Expected behavior**
a button at the top of the character sheet to revert the transformation

**Screenshots**
![Screenshot 2022-07-09 014223](https://user-images.githubusercontent.com/32625656/178093519-26a774d0-d691-494a-b8d6-563c6879e8dc.png)

**Browser:**
 - Opera

**Foundry Version:** Version 9

**Game System:** DnD5e 1.6.3

**Comment by p4535992** [comment]
Added on version 1.0.42, but beware there are other issues hidden in the dark. 
P.S. If you don' want the default long name you can set a explicit name on the configuration dialog next to the name of the actor.

**Comment by CasualTerror** [comment]
The button how there but it doesn't restore the token. and checking the explicit name of the transformed actor just changes the token name to 'true'.

![Screenshot 2022-07-09 130451](https://user-images.githubusercontent.com/32625656/178115824-362834d4-615e-4e5a-99b2-3cbb6bfcec98.png)

**Comment by p4535992** [comment]
Try out version 1.0.43.
