### ISSUE TITLE
Call PolymorpherManager through Macro

### ISSUE THREAD

**Issue by JamesBrandts** [p4535992/foundryvtt-automated-polymorpher#2]
I was trying, without success, to make a macro to call the PolymorpherManager through a macro, so I could make a macro shortcut or include it in the Wild Shape/Polymorph Items instead of having to open the sheet and clicking in the icon. Probably this feature already exists in the module, but I couldn't figure it out.
Amazing module, thanks for building and making it available.

**Comment by p4535992** [comment]
Add api and hud button configuration., on version1.0.16, try out and let me know it!

**Comment by JamesBrandts** [comment]
Wow, this is even better than I expected, can't wait till my Druid player sees this, she'll be stunned, as I'm right now.
The HUD button works perfectly, the Wild Shape feature call the macro, just one click and everything is done. Ready to bite some goblin heads off.
"Revert to normal form?" Right click in the token, right click on the HUD, done.
Couldn't ask for more.
Thank you so much

**Comment by p4535992** [comment]
Sorry to bother @JamesBrandts but are you by chance the james of https://www.patreon.com/jamesrpgart ?

**Comment by JamesBrandts** [comment]
No, unfortunately not, wish I could make that kind of art.
