### ISSUE TITLE
[BUG] Latest release not working on newly upgraded server

### ISSUE THREAD

**Issue by Eireman** [p4535992/foundryvtt-automated-polymorpher#23]
On opening the POLYMORPH window, we can generate the actors, but on select it only minimizes the POLYMORPH window and does not call the feature select (for wildshape, poly, etc.).

Any clue?
![polymorph bug](https://user-images.githubusercontent.com/112606485/192172446-157568e2-349f-4e75-adc1-2fe223568186.png)

**Comment by p4535992** [comment]
**Module Version:** 
**System Version:**
**FoundryVTT Version:**

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.

**Comment by Eireman** [comment]
Confirmed fixed.
