### ISSUE TITLE
Pathfinder 2e compatibility

### ISSUE THREAD

**Issue by yoannfelix** [p4535992/foundryvtt-automated-polymorpher#3]
Is this module not compatible with Pathfinder 2e?
I ran it with the following modules enabled and it did not work-

- Advanced Macros
- Automated Evocations - Polymorpher Manager.
- Module Management+
- Sequencer
- socketlib
- Warp Gate.

Is there something I am missing or is it not compatible with Pf2e yet? I was able to get it to work on 5e.

**Comment by p4535992** [comment]
workin in progress, the time is always the problem... can't say when i can give to you a working release

**Comment by p4535992** [comment]
@yoannfelix  try out  version 1.0.20 and let me know for any issue

**Comment by yoannfelix** [comment]
It worked!

There was no 'restore transformation' but a 'revert' button. Was that intentional? There was no animation transforming back which I don't mind but should open a separate enhancement for that?

**Comment by p4535992** [comment]
a i got it... leave this tiket open...

**Comment by p4535992** [comment]
Should be finally fixed with 1.0.23
