### ISSUE TITLE
[BUG] Remove “automated evocations “ name from module name

### ISSUE THREAD

**Issue by theripper93** [p4535992/foundryvtt-automated-polymorpher#32]
Since people are coming to my discord channel for troubleshooting your module, I’d be great full if my module name was not used in your module name, not sure why this is in the first place, I’m also not an author for this module

![](https://cdn.discordapp.com/attachments/1065453169448071189/1065454913364172901/image.png)

**Comment by p4535992** [comment]
I am really sorry for the inconvenience I caused you, I have removed the label "Evocation" and your reference from the list of authors. It should now be "not misleading".

**Comment by theripper93** [comment]
It is still in the manifest.json

**Comment by p4535992** [comment]
ok yes sorry i meant i updated the github project as soon as i get home i will update the foundryvtt page.
