### ISSUE TITLE
"Keep Self" Missing

### ISSUE THREAD

**Issue by Shareenx** [p4535992/foundryvtt-automated-polymorpher#4]
* Foundry VTT Version: 9.266
* Operating System: Windows
* Using Foundry: Chrome
* Game System: dnd5e
* Modules Enabled?: Yes. Automated Evocations- Polymorph Manager, socketlib, Sequencer, Warpgate

I am pretty sure this is user error or misunderstanding. I can swear I saw the option to "Keep Self" in the Polymorph UI before some update or another. Now, with or without modules enabled, I do not see it. Therefore, when using Disguise Self or Alter Self and want to just change the token image, the HP on the actor change to the polymorph target's. 
I've attached a screen shot of the UI in question from your wiki with the highlighted part I do not have (Expected), plus one of mine (Actual), and my core and module settings.

This is driving me batty! Argh!

thanks!
Sakura

![Actual](https://user-images.githubusercontent.com/81126418/163235307-27e86851-bae6-4c4d-82b5-ace2671f1d11.PNG)
![Core](https://user-images.githubusercontent.com/81126418/163235316-f1686c6a-fb79-4e23-bd32-fac8a3ad574f.PNG)
![Expected](https://user-images.githubusercontent.com/81126418/163235320-e815a18b-6e23-470d-9578-e3ecf3f94ed6.PNG)
![module](https://user-images.githubusercontent.com/81126418/163235323-1068cebb-5997-41a7-a476-984b80d070d6.PNG)

**Comment by p4535992** [comment]
Sorry, no that's a PR i open on the dnd5e system https://gitlab.com/foundrynet/dnd5e/-/merge_requests/439.
I must have taken the screenshot on my developing world.
Should be merge on version 1.6.0 of the dnd5e system.

**Comment by Shareenx** [comment]
Oh thank heavens, I thought I was going batty.
Thanks!!!
