### ISSUE TITLE
Reverting transformation playing animtion in wrong place.

### ISSUE THREAD

**Issue by calopsychic** [p4535992/foundryvtt-automated-polymorpher#8]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

* Foundry VTT Version: 9 - Build 269
* Operating System: Windows 10
* How Are You Using Foundry: Chrome
* Which Game System: DnD 5e
* Modules Enabled?: Yes, don't think any of them are the cause of the bug.

### Issue

Moving a token and transforming back to its original form plays the animation where the token originally was placed, even if reloading the scene or application.

![image](https://user-images.githubusercontent.com/94251391/168458721-bad19575-65dc-4222-9a9c-c425dd5fb06f.png)

Picture taken as the token was reverting.

**Comment by p4535992** [comment]
Seem to work on my test world , make sure to us ethe latest release 1.0.24
